version: '3'

services:
    nginx:
        image: nginx:latest
        container_name: nginx
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./conf.d:/etc/nginx/conf.d
            - ./application:/var/www/html/
            - ./logs/nginx:/var/log/nginx
        links:
            - php
    php:
        build: ./php
        container_name: php
        volumes:
            - ./application:/var/www/html/
        extra_hosts:
            - "host.docker.internal:host-gateway"
            - "hostlocal:127.0.0.1"
            - "hostlocaltwo:192.168.2.29"
    chrome:
        image: selenium/standalone-chrome:4.3.0-20220706
        container_name: selenium-chrome
        shm_size: 2gb
        ports:
            - "4444:4444"
        extra_hosts:
            - "host.docker.internal:host-gateway"
            - "hostlocal:127.0.0.1"
            - "hostlocaltwo:192.168.2.29"
    # browsermobproxy:
    #     build: ./browsermobproxy
    #     container_name: browsermob-proxy
    #     volumes:
    #         - ./application:/var/www/html/
    browsermobproxy:
        image: bwowk/browsermob-proxy
        container_name: browsermob-proxy
        ports:
            - "58080:8080"
            - "58200:8200"
        extra_hosts:
            - "host.docker.internal:host-gateway"
            - "hostlocal:127.0.0.1"
            - "hostlocaltwo:192.168.2.29"
    # firefox:
    #     image: selenium/standalone-firefox:4.3.0-20220706
    #     container_name: selenium-firefox
    #     shm_size: 2gb
    #     ports:
    #         - "4444:4444"
    #     volumes:
    #         - ./harext:/var/local/
    # db:
    #     image: mysql
    #     container_name: mysql
    #     restart: always
    #     environment:
    #         MYSQL_RANDOM_ROOT_PASSWORD: yes
    #         MYSQL_USER: comprendo
    #         MYSQL_PASSWORD: qwerty

    # adminer:
    #     image: adminer
    #     container_name: mysql-adminer
    #     restart: always
    #     ports:
    #         - 8080:8080
    # chrome:
    #     image: selenium/standalone-chrome:4.3.0-20220706
    #     container_name: selenium-chrome
    #     shm_size: 2gb
    #     depends_on:
    #         - selenium-hub
    #     environment:
    #         - SE_EVENT_BUS_HOST=selenium-hub
    #         - SE_EVENT_BUS_PUBLISH_PORT=4442
    #         - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    #     ports:
    #         - "5900:5900"
    #         - "4444:4444"
    # selenium-hub:
    #     image: selenium/hub:4.3.0-20220706
    #     container_name: selenium-hub
    #     ports:
    #     - "4442:4442"
    #     - "4443:4443"
    #     - "4444:4444"